project_id = "open-sauced-supabase-cron-test"

[api]
port = 54321
schemas = []
extra_search_path = []
max_rows = 1000

[db]
port = 54322
major_version = 14
minor_version = 1

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"
jwt_expiry = 3600
enable_signup = false
