-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.users_to_repos_stars
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL REFERENCES public.users (id),
    repo_id bigint NOT NULL REFERENCES public.repos (id),
    created_at timestamp with time zone DEFAULT now(),

    CONSTRAINT stars_pkey PRIMARY KEY (id),
    CONSTRAINT stars_hash UNIQUE (user_id, repo_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users_to_repos_stars
    OWNER to postgres;

GRANT ALL ON TABLE public.users_to_repos_stars TO anon;

GRANT ALL ON TABLE public.users_to_repos_stars TO authenticated;

GRANT ALL ON TABLE public.users_to_repos_stars TO postgres;

GRANT ALL ON TABLE public.users_to_repos_stars TO service_role;
