-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.stars
(
    id bigint NOT NULL,
    stargazers_count bigint,
    open_issues_count bigint,
    forks_count bigint,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT stars_pkey PRIMARY KEY (id),
    CONSTRAINT stars_full_name_key UNIQUE (full_name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.stars
    OWNER to postgres;

GRANT ALL ON TABLE public.stars TO anon;

GRANT ALL ON TABLE public.stars TO authenticated;

GRANT ALL ON TABLE public.stars TO postgres;

GRANT ALL ON TABLE public.stars TO service_role;
