name: Populate the Supabase
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: "supabase-populate"
  cancel-in-progress: false

jobs:
  populate-the-supabase:
    name: run update
    runs-on: ubuntu-latest
    steps:
      - name: "check env"
        run: echo ${{ github.ref }}

      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "📦 install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "🔍 populate supabase"
        run: npm run start
        env:
          OPEN_SAUCED_APP_ID: ${{ secrets.OPEN_SAUCED_APP_ID }}
          OPEN_SAUCED_PRIVATE_KEY: ${{ secrets.OPEN_SAUCED_PRIVATE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          LIMIT_DAYS: 1
          LIMIT_USERS: 3

      - name: "🚀 Commit changes"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ./src/*.json
          commit_message: "chore: update supabase data [skip ci]"
          commit_user_name: 0-vortex
          commit_user_email: 237133+0-vortex@users.noreply.github.com
